#!/usr/bin/env python

import sys

sys.path.append("src")
from Vector import Vector

vec = Vector()

if len(sys.argv) > 1:
    if sys.argv[1] in ["-h", "--help"]:
        print "Usage: ./vector.py [file.vec]"
        exit()
    try:
        stream = open(sys.argv[1]).read()
    except:
        print "No such file or directory: " + sys.argv[1]
        exit()
    else:
        vec.eval(stream)
else:
    while True:
        stream = raw_input("Vec> ")
        vec.eval(stream)
